apiVersion: apps/v1
kind: Deployment

metadata:
  name: mydeployment
  labels:
    app: myapp

spec:
  replicas: 6

  selector:
    matchLabels:
      app: myapp

  template:
    metadata:
      labels:
        app: myapp

    spec:
      containers:
        - name: mycontainer
          image: docker.io/atuljkamble/storefront:latest
          ports:
            - containerPort: 3000
