apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: webapp-scaler
  namespace: default
spec:
  scaleTargetRef:
    name: webapp
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "50"
